
[build]
  functions = "netlify/functions"
  publish = "public"

[functions]
  directory = "netlify/functions"

[dev]
  functions = "netlify/functions"

# Optional headers for better security and CORS handling
[[headers]]
  for = "/.netlify/functions/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Headers = "Content-Type"
